version: '3'

services:
  db:
    image: nouchka/sqlite3
  web:
    image: jeremyakd/la-caffettiera:1.0.1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
